name: CI workflow
          
on:       
  push:   
  pull_request:
    branches: [ "main" ]
          
jobs:     
  # ===== CPU SERIAL BUILD =====
  build-cpu:  
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Install build tools and linter
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libopenmpi-dev openmpi-bin

      - name: Run gen_OPALrevision
        run: |
          chmod +x ./gen_OPALrevision
          ./gen_OPALrevision
          
      - name: Configure CMake project
        run: |
          mkdir -p build_serial
          cd build_serial
          cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_STANDARD=20 \
            -DIPPL_ENABLE_FFT=ON \
            -DIPPL_ENABLE_SOLVERS=ON \
            -DIPPL_ENABLE_ALPINE=OFF \
            -DIPPL_ENABLE_TESTS=OFF \
            -DIPPL_PLATFORMS=serial
          
      - name: Build project
        run: |
          cd build_serial
          make -j$(nproc)
          
  # ===== GPU CUDA BUILD =====
  build-cuda:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.8.1-devel-ubuntu22.04  # CUDA-enabled container for compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies + CMake 4.1.1
        run: |
          apt-get update
          apt-get install -y build-essential git wget p7zip-full libopenmpi-dev openmpi-bin
          wget https://cmake.org/files/v4.1/cmake-4.1.1-linux-x86_64.sh
          bash cmake-4.1.1-linux-x86_64.sh --skip-license --prefix=/usr/local
          cmake --version
      
      - name: Run gen_OPALrevision
        run: |
          chmod +x ./gen_OPALrevision
          ./gen_OPALrevision

      - name: Configure CMake project (CUDA)
        run: |
          mkdir -p build_cuda
          cd build_cuda
          cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DIPPL_PLATFORMS=CUDA \
            -DKokkos_ARCH_AMPERE80=ON \
            -DCMAKE_CXX_STANDARD=20 \
            -DIPPL_ENABLE_FFT=ON \
            -DIPPL_ENABLE_SOLVERS=ON \
            -DIPPL_ENABLE_ALPINE=OFF \
            -DIPPL_ENABLE_TESTS=OFF
          
      - name: Build project
        run: |
          cd build_cuda
          make -j$(nproc)
